settings:
  title: 'Operant.io Uptime Page'
  url: 'https://uptime.operant.io' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 7 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: plex-operant-io # unique identifier
    name: Plex Media Server
    url: 'https://plex.operant.io:32500' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-operant-io
    name: operant.io
    description: 'operant.io landing page'
    url: 'https://operant.io'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: operant-blog
    name: operant blog
    url: 'https://operant.blog/'
    method: GET
    expectStatus: 200
    linkable: true